// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ReturnInputC
String ReturnInputC(String line);
RcppExport SEXP _lipidProfillingRM_ReturnInputC(SEXP lineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type line(lineSEXP);
    rcpp_result_gen = Rcpp::wrap(ReturnInputC(line));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lipidProfillingRM_ReturnInputC", (DL_FUNC) &_lipidProfillingRM_ReturnInputC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_lipidProfillingRM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
